### ISSUE TITLE
Fail to serializer PyTorch model as WXF

### ISSUE THREAD

**Issue by GalAster** [WolframResearch/WolframClientForPython#1]
I am trying to convert some PyTorch models into WLNet models.

PyTorch models are generally saved as pth files.

A `*.pth` file is a `collections.OrderedDict` of `torch.tensor`, it looks like: 

```python
OrderedDict([
	('name.weights', tensor([64×3×3×3])),
	('name.biases', tensor([64])),
])
```

I expect them to be converted into the following results: 

```Mathematica
<|
	"name.weights" -> RawData[64×3×3×3],
	"name.biases" -> RawData[64]
|>
```

---

But I have encountered some problems, `torch.tensor` can not be converted.

```python
import torch
import wolframclient.serializers as wxf
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
wxf.export(x, 'tensor.wxf', target_format='wxf')
```

```log
Traceback (most recent call last):
File "<input>", line 1, in <module>
File "C:\Anaconda3\lib\wolframclient\serializers\__init__.py", line 60, in export data, stream=stream)
File "C:\Anaconda3\lib\wolframclient\serializers\base.py", line 22, in export self.dump(data, file)
File "C:\Anaconda3\lib\wolframclient\serializers\wxf.py", line 54, in dump for payload in self.normalize(data):
File "C:\Anaconda3\lib\wolframclient\utils\dispatch.py", line 96, in inner return self.resolve(function, *args)(obj, *args, **opts)
File "C:\Anaconda3\lib\wolframclient\serializers\normalizer\__init__.py", line 21, in normalizer return self.serialize_iterable(self.normalize(value) for value in o)
File "C:\Anaconda3\lib\wolframclient\serializers\base.py", line 72, in serialize_iterable self.serialize_symbol(b'List'), iterable, **opts)
File "C:\Anaconda3\lib\wolframclient\serializers\wxf.py", line 67, in serialize_function iterable, length = get_length(args, **opts)
File "C:\Anaconda3\lib\wolframclient\serializers\wxf.py", line 27, in get_length iterable = tuple(iterable)
File "C:\Anaconda3\lib\wolframclient\serializers\normalizer\__init__.py", line 21, in <genexpr> return self.serialize_iterable(self.normalize(value) for value in o)
File "C:\Anaconda3\lib\wolframclient\utils\dispatch.py", line 96, in inner return self.resolve(function, *args)(obj, *args, **opts)
File "C:\Anaconda3\lib\wolframclient\serializers\normalizer\__init__.py", line 21, in normalizer return self.serialize_iterable(self.normalize(value) for value in o)
File "C:\Anaconda3\lib\wolframclient\serializers\base.py", line 72, in serialize_iterable self.serialize_symbol(b'List'), iterable, **opts)
File "C:\Anaconda3\lib\wolframclient\serializers\wxf.py", line 67, in serialize_function iterable, length = get_length(args, **opts)
File "C:\Anaconda3\lib\wolframclient\serializers\wxf.py", line 27, in get_length iterable = tuple(iterable)
File "C:\Anaconda3\lib\wolframclient\serializers\normalizer\__init__.py", line 21, in <genexpr> return self.serialize_iterable(self.normalize(value) for value in o)
File "C:\Anaconda3\lib\wolframclient\utils\dispatch.py", line 96, in inner return self.resolve(function, *args)(obj, *args, **opts)
File "C:\Anaconda3\lib\wolframclient\serializers\normalizer\__init__.py", line 21, in normalizer return self.serialize_iterable(self.normalize(value) for value in o)
File "C:\Anaconda3\lib\torch\tensor.py", line 381, in __iter__ raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor
```

But I think  `torch.tensor` just the same as `numpy.ndarray`.

How can I solve this problem.

**Comment by DbxDev** [comment]
I'm not an expert of Torch but the torch tensor method `numpy()` seems to do what you need:

`wxf.export(x.numpy(), target_format='wxf')`

Note that even though torch tensor and numpy array can share the underlying memory, they are not the same object.

The error you witness is raised by torch. The WXF serializer does not recognize torch tensor, but can serialize iterable objects, and torch tensors are iterable objects. When working on a matrix, first iteration targets rows, second targets 0 dimension tensor, i.e matrix elements wrapped into a tensor. Those are iterable, but it's an invalid operation which raises an error.

From your torsor x:
``` python
for row in x:
   for elem in row:
       print(elem, 'is iterable?', hasattr(elem, '__iter__'))
```

**Comment by GalAster** [comment]
Nice, this works.

I think we can provide some pre-defined methods to convert some common files, such as `*.pkl`, `*.npz` etc.

This should be useful:

```python
#!/usr/bin/env python
# coding=utf-8
import torch
import pickle
import numpy
import wolframclient.serializers as wxf

def pkl2wxf(path):
	file = open(path, 'rb')
	objs = []
	while True:
		try : objs.append(pickle.load(file))
		except EOFError : break
	file.close()
	print(objs)
	wxf.export(objs, path + '.wxf', target_format='wxf')

def npy2wxf(path):
	data = numpy.load(path)
	wxf.export(data, path + '.wxf', target_format='wxf')

def pth2wxf(path):
	pth = torch.load(path, map_location=torch.device('cpu'))
	npy = {key: value.numpy() for key, value in pth.items()}
	wxf.export(npy, path + '.wxf', target_format='wxf')

pth2wxf('checkpoint.pth')
```
