### ISSUE TITLE
TypeError when running setup.py test

### ISSUE THREAD

**Issue by doronbehar** [WolframResearch/WolframClientForPython#18]
I'd like to package wolframclient for NixOS and I encounter this error when our build system runs `python setup.py test`:

```
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 78, in <module>
    'wolframclient_serializers_encoder':[]
  File "/nix/store/110cqfw7ncbn4haynn8x8ziwzmr55dlg-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nix/store/110cqfw7ncbn4haynn8x8ziwzmr55dlg-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/command/test.py", line 238, in run
    self.run_tests()
  File "/nix/store/110cqfw7ncbn4haynn8x8ziwzmr55dlg-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/command/test.py", line 260, in run_tests
    exit=False,
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/main.py", line 159, in createTests
    self.module)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/build/wolframclient-1.1.2/setup.py", line 78, in <module>
    'wolframclient_serializers_encoder':[]
  File "/nix/store/110cqfw7ncbn4haynn8x8ziwzmr55dlg-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nix/store/110cqfw7ncbn4haynn8x8ziwzmr55dlg-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/command/test.py", line 238, in run
    self.run_tests()
  File "/nix/store/110cqfw7ncbn4haynn8x8ziwzmr55dlg-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/command/test.py", line 260, in run_tests
    exit=False,
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/main.py", line 159, in createTests
    self.module)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
  File "/build/wolframclient-1.1.2/setup.py", line 40, in load_tests
    TestCommand().handle()
  File "/build/wolframclient-1.1.2/wolframclient/cli/commands/test.py", line 84, in handle
    result = runner.run(suite)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/runner.py", line 153, in run
    result = self._makeResult()
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/runner.py", line 149, in _makeResult
    return self.resultclass(self.stream, self.descriptions, self.verbosity)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/unittest/runner.py", line 40, in __init__
    self.showAll = verbosity > 1
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by DbxDev** [comment]
There is indeed a problem when running tests from setup.py (which we never do). I'll fix this bug.
In the mean time if you'd like to run tests, you should use: 
`python3 run.py test` 

Additional info may be found using: 

`python3.7 run.py test --help`

Please note that testing requires a bit of configuration as (quickly) explained in the sample configuration file [local_config_sample.json](https://github.com/WolframResearch/WolframClientForPython/blob/master/wolframclient/tests/local_config_sample.json). Some fields may be safely removed, related tests will be skipped (e.g. if "cloud_credentials" is missing cloud tests will be skipped). Speaking of cloud tests, a lot of them rely on Wolfram APIs that must be deployed beforehand. They can be found in [api.m](https://github.com/WolframResearch/WolframClientForPython/blob/master/wolframclient/tests/evaluation/api.m).

**Comment by DbxDev** [comment]
Fixed. Update will appear in next release.
