### ISSUE TITLE
Cannot serialize object of class numpy.float32

### ISSUE THREAD

**Issue by GalAster** [WolframResearch/WolframClientForPython#2]
```python
import numpy
import wolframclient.serializers as wxf
wxf.export(numpy.float32(0))
```

Version: 
- numpy 1.15.3 
- WolframClient1.0.0.dev2

```log
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "c:\Anaconda3\lib\site-packages\wolframclient\serializers\__init__.py", line 60, in export
    data, stream=stream)
  File "c:\Anaconda3\lib\site-packages\wolframclient\serializers\base.py", line 29, in export
    stream = self.dump(data, stream)
  File "c:\Anaconda3\lib\site-packages\wolframclient\serializers\wl.py", line 31, in dump
    for payload in self.normalize(data):
  File "c:\Anaconda3\lib\site-packages\wolframclient\utils\dispatch.py", line 96, in inner
    return self.resolve(function, *args)(obj, *args, **opts)
  File "c:\Anaconda3\lib\site-packages\wolframclient\serializers\normalizer\__init__.py", line 26, in normalizer
    'Cannot serialize object of class %s' % o.__class__)
NotImplementedError: Cannot serialize object of class <class 'numpy.float32'>
```

**Comment by riccardodivirgilio** [comment]
We currently don't support the serialization of a single type, only array serialization.

to export using wxf you need to do export(..., target_format = 'wxf'), the default is wl (InputForm).

**Comment by DbxDev** [comment]
We plan to provide better integration for various popular libraries. 
For the moment we use numpy to represent Wolfram Language numeric arrays, since that's the most reasonable thing to do in Python, but don't provide full integration of the numpy library. Not yet at least.
