### ISSUE TITLE
wolframclient.exception.WolframParserException: Invalid version b''.

### ISSUE THREAD

**Issue by JuanG970** [WolframResearch/WolframClientForPython#37]
I am trying to run the client on MacOS and Mathematica 13.3, but I am getting the following error after running:
```
Python 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wolframclient.evaluation import WolframLanguageSession
>>> from wolframclient.language import wl, wlexpr
>>> session.evaluate(wlexpr('Range[5]'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/evaluation/kernel/localsession.py", line 262, in evaluate
    result = self.evaluate_wrap(expr, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/evaluation/kernel/localsession.py", line 259, in evaluate_wrap
    return self.evaluate_wrap_future(expr, **kwargs).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/evaluation/kernel/kernelcontroller.py", line 583, in run
    self._do_evaluate(payload, future, result_update_callback)
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/evaluation/kernel/kernelcontroller.py", line 543, in _do_evaluate
    for msg in result.iter_messages():
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/evaluation/result.py", line 118, in iter_messages
    if self.messages:
       ^^^^^^^^^^^^^
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/evaluation/result.py", line 103, in messages
    self.build()
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/evaluation/result.py", line 155, in build
    self.parse_response()
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/evaluation/result.py", line 245, in parse_response
    self.parsed_response = binary_deserialize(self.wxf_evaluation_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/deserializers/wxf/__init__.py", line 35, in binary_deserialize
    parser = WXFParser(wxf_input)
             ^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/deserializers/wxf/wxfparser.py", line 88, in __init__
    version, compress = self.parse_header()
                        ^^^^^^^^^^^^^^^^^^^
  File "/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/deserializers/wxf/wxfparser.py", line 107, in parse_header
    raise WolframParserException("Invalid version %s." % next_byte)
wolframclient.exception.WolframParserException: Invalid version b''.
```

What could be the issue? What does the constant [WXF_VERSION](https://github.com/WolframResearch/WolframClientForPython/blob/27cffef560eea8d16c02fe4086f42363604284b6/wolframclient/serializers/wxfencoder/constants.py#L23) means?

**Comment by riccardodivirgilio** [comment]
Without going into too many details the WXF format is used to exchange data. It is a binary payload that starts with a manifest that includes the version of the format itself.

https://reference.wolfram.com/language/tutorial/WXFFormatDescription.html

I would like you to do several things:

1. I notice from your stack trace that you are directly using the library that is provided with a Mathematica installation, which is not recommended. Can you try to see if the same code runs ok if you use pip to install it?

2. Evaluate the content of `SystemInformation["Small"]` in your Mathematica installation and give me the value here.

3. Print the content of the `wxf_input` variable by adding a print statement in this line:

```
"/Applications/Mathematica.app/Contents/SystemFiles/Components/WolframClientForPython/wolframclient/deserializers/wxf/__init__.py", line 35, in binary_deserialize
    parser = WXFParser(wxf_input)
```

thanks

**Comment by JuanG970** [comment]
Thank you for your response. Addressing your previous points:

1. I tried to run it with the pip install with no luck, the same error
2. This is the output of `SystemInformation["Small"]`
``` 
{"Kernel" -> {"SystemID" -> "MacOSX-x86-64", 
   "ReleaseID" -> "13.3.0.0 (8661523, 2023060320016)", 
   "CreationDate" -> 
    DateObject[{2023, 6, 3, 3, 4, 44}, "Instant", "Gregorian", -6.], 
   "OperatingSystemVersion" -> "macOS 13.5 (22G74)"}, 
 "FrontEnd" -> {"SystemID" -> "MacOSX-x86-64", 
   "ReleaseID" -> "13.3.0.0 (8661523, 2023060312247)", 
   "CreationDate" -> 
    DateObject[{2023, 6, 3, 3, 15, 32}, "Instant", "Gregorian", -6.], 
   "OperatingSystemVersion" -> "13.5 (22G74)"}
} 
```
3. I added the print statement, but it returns a memory address (`<memory at 0x10cc40700>`) does that tell you something?
```
Python 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wolframclient.evaluation import WolframLanguageSession
>>> from wolframclient.language import wl, wlexpr
>>> session = WolframLanguageSession()
>>> session.evaluate(wlexpr('Range[5]'))
wxf_input: <memory at 0x10cc40700>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/wolframclient/evaluation/kernel/localsession.py", line 262, in evaluate
    result = self.evaluate_wrap(expr, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wolframclient/evaluation/kernel/localsession.py", line 259, in evaluate_wrap
    return self.evaluate_wrap_future(expr, **kwargs).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/wolframclient/evaluation/kernel/kernelcontroller.py", line 583, in run
    self._do_evaluate(payload, future, result_update_callback)
  File "/usr/local/lib/python3.11/site-packages/wolframclient/evaluation/kernel/kernelcontroller.py", line 543, in _do_evaluate
    for msg in result.iter_messages():
  File "/usr/local/lib/python3.11/site-packages/wolframclient/evaluation/result.py", line 118, in iter_messages
    if self.messages:
       ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wolframclient/evaluation/result.py", line 103, in messages
    self.build()
  File "/usr/local/lib/python3.11/site-packages/wolframclient/evaluation/result.py", line 155, in build
    self.parse_response()
  File "/usr/local/lib/python3.11/site-packages/wolframclient/evaluation/result.py", line 245, in parse_response
    self.parsed_response = binary_deserialize(self.wxf_evaluation_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wolframclient/deserializers/wxf/__init__.py", line 36, in binary_deserialize
    parser = WXFParser(wxf_input)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wolframclient/deserializers/wxf/wxfparser.py", line 88, in __init__
    version, compress = self.parse_header()
                        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wolframclient/deserializers/wxf/wxfparser.py", line 107, in parse_header
    raise WolframParserException("Invalid version %s." % next_byte)
wolframclient.exception.WolframParserException: Invalid version b''.
```

**Comment by JuanG970** [comment]
Any more ideas on how to fix this? I can provide more help if needed

**Comment by JuanG970** [comment]
I don't see this failure after updating to Mathematica 14.0 and re-installing the client.
